=== api-evangelist/amazon-connect/json-schema/amazon-connect-user-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/User",
  "title": "User",
  "type": "object",
  "description": "Contains information about a user account for an Amazon Connect instance.",
  "properties": {
    "Id": {
      "type": "string",
      "description": "The identifier of the user account.",
      "example": "500123"
    },
    "Arn": {
      "type": "string",
      "description": "The Amazon Resource Name (ARN) of the user account.",
      "example": "arn:aws:connect:us-east-1:123456789012:instance/a1b2c3d4/agent/500123"
    },
    "Username": {
      "type": "string",
      "description": "The user name assigned to the user account.",
      "example": "jsmith"
    },
    "IdentityInfo": {
      "$ref": "#/components/schemas/UserIdentityInfo"
    },
    "PhoneConfig": {
      "$ref": "#/components/schemas/UserPhoneConfig"
    },
    "DirectoryUserId": {
      "type": "string",
      "description": "The identifier of the user account in the directory service that Amazon Connect uses to authenticate users."
    },
    "SecurityProfileIds": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "The identifiers of the security profiles for the user."
    },
    "RoutingProfileId": {
      "type": "string",
      "description": "The identifier of the routing profile for the user.",
      "example": "a1b2c3d4-5678-90ab-cdef-33333EXAMPLE"
    },
    "HierarchyGroupId": {
      "type": "string",
      "description": "The identifier of the hierarchy group for the user."
    },
    "Tags": {
      "type": "object",
      "description": "The tags.",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}

=== api-evangelist/amazon-connect/examples/user-example.json
{
  "Id": "500123",
  "Arn": "arn:aws:connect:us-east-1:123456789012:instance/a1b2c3d4/agent/500123",
  "Username": "jsmith",
  "IdentityInfo": "a1b2c3d4-5678-90ab-cdef-11111EXAMPLE",
  "PhoneConfig": "+12065551212",
  "DirectoryUserId": "a1b2c3d4-5678-90ab-cdef-11111EXAMPLE",
  "SecurityProfileIds": [
    "a1b2c3d4-5678-90ab-cdef-11111EXAMPLE"
  ],
  "RoutingProfileId": "a1b2c3d4-5678-90ab-cdef-33333EXAMPLE",
  "HierarchyGroupId": "a1b2c3d4-5678-90ab-cdef-11111EXAMPLE",
  "Tags": {
    "key": "value"
  }
}
