=== api-evangelist/amazon-connect/json-schema/amazon-connect-routingprofile-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/RoutingProfile",
  "title": "RoutingProfile",
  "type": "object",
  "description": "Contains information about a routing profile.",
  "properties": {
    "InstanceId": {
      "type": "string",
      "description": "The identifier of the Amazon Connect instance."
    },
    "Name": {
      "type": "string",
      "description": "The name of the routing profile.",
      "example": "Voice Agents"
    },
    "RoutingProfileArn": {
      "type": "string",
      "description": "The Amazon Resource Name (ARN) of the routing profile."
    },
    "RoutingProfileId": {
      "type": "string",
      "description": "The identifier of the routing profile.",
      "example": "a1b2c3d4-5678-90ab-cdef-33333EXAMPLE"
    },
    "Description": {
      "type": "string",
      "description": "The description of the routing profile."
    },
    "MediaConcurrencies": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/MediaConcurrency"
      }
    },
    "DefaultOutboundQueueId": {
      "type": "string",
      "description": "The identifier of the default outbound queue for this routing profile."
    },
    "Tags": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "NumberOfAssociatedQueues": {
      "type": "integer",
      "description": "The number of associated queues in routing profile."
    },
    "NumberOfAssociatedUsers": {
      "type": "integer",
      "description": "The number of associated users in routing profile."
    }
  }
}

=== api-evangelist/amazon-connect/examples/routing-profile-example.json
{
  "InstanceId": "a1b2c3d4-5678-90ab-cdef-11111EXAMPLE",
  "Name": "Voice Agents",
  "RoutingProfileArn": "arn:aws:connect:us-east-1:123456789012:instance/a1b2c3d4",
  "RoutingProfileId": "a1b2c3d4-5678-90ab-cdef-33333EXAMPLE",
  "Description": "A description of the resource.",
  "MediaConcurrencies": [
    "example-value"
  ],
  "DefaultOutboundQueueId": "a1b2c3d4-5678-90ab-cdef-11111EXAMPLE",
  "Tags": {
    "key": "value"
  },
  "NumberOfAssociatedQueues": 0,
  "NumberOfAssociatedUsers": 0
}
