=== api-evangelist/amazon-connect/json-schema/create-user-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-connect/refs/heads/main/json-schema/create-user-request-schema.json",
  "title": "CreateUserRequest",
  "description": "CreateUserRequest schema from Amazon Connect Service API",
  "type": "object",
  "properties": {
    "Username": {
      "type": "string",
      "description": "The user name for the account.",
      "example": "jsmith"
    },
    "Password": {
      "type": "string",
      "description": "The password for the user account."
    },
    "IdentityInfo": {
      "$ref": "#/components/schemas/UserIdentityInfo"
    },
    "PhoneConfig": {
      "$ref": "#/components/schemas/UserPhoneConfig"
    },
    "DirectoryUserId": {
      "type": "string"
    },
    "SecurityProfileIds": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "The identifier of the security profile for the user."
    },
    "RoutingProfileId": {
      "type": "string",
      "description": "The identifier of the routing profile for the user.",
      "example": "a1b2c3d4-5678-90ab-cdef-33333EXAMPLE"
    },
    "HierarchyGroupId": {
      "type": "string"
    },
    "Tags": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  },
  "required": [
    "PhoneConfig",
    "RoutingProfileId",
    "SecurityProfileIds",
    "Username"
  ]
}

=== api-evangelist/amazon-connect/examples/create-user-request-example.json
{
  "Username": "jsmith",
  "Password": "TempPass123!",
  "IdentityInfo": "a1b2c3d4-5678-90ab-cdef-11111EXAMPLE",
  "PhoneConfig": "+12065551212",
  "DirectoryUserId": "a1b2c3d4-5678-90ab-cdef-11111EXAMPLE",
  "SecurityProfileIds": [
    "a1b2c3d4-5678-90ab-cdef-11111EXAMPLE"
  ],
  "RoutingProfileId": "a1b2c3d4-5678-90ab-cdef-33333EXAMPLE",
  "HierarchyGroupId": "a1b2c3d4-5678-90ab-cdef-11111EXAMPLE",
  "Tags": {
    "key": "value"
  }
}
